en:
  languageName: English
  weight: 2
  contentDir: content/en
  title: Algosphere Alliance
  params:
    description: "for the alleviation of suffering"
fr:
  languageName: Français
  weight: 4
  contentDir: content/fr
  title: Alliance Algosphère
  params:
    description: "pour l'allègement de la souffrance"
