main:
- identifier: accueil
  name: Accueil
  url: /
  weight: 1
- identifier: vision
  name: Vision
  url: /vision/
  weight: 2
- identifier: positions
  name: Positions
  url: /positions/
  weight: 3
- identifier: positions-structurelles
  name: Structurelles
  url: /positions/structurelles/
  parent: positions
  weight: 1
- identifier: positions-ponctuelles
  name: Ponctuelles
  url: /positions/ponctuelles/
  parent: positions
  weight: 2
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 4
- identifier: organisations
  name: Organisations
  url: /organisations/
  weight: 5
- identifier: algoconseil
  name: AlgoConseil
  url: /algoconseil/
  weight: 6
- identifier: gouvernance
  name: Gouvernance
  url: /gouvernance/
  weight: 7
- identifier: constitution
  name: Constitution
  url: /gouvernance/constitution/
  parent: gouvernance
  weight: 1
- identifier: faq
  name: FAQ
  url: /gouvernance/faq/
  parent: gouvernance
  weight: 2
- identifier: l-alliance-en-images
  name: L'Alliance en images
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 8
footer:
- identifier: mentions-legales
  name: Mentions légales
  url: /mentions-legales/
  weight: 1
