main:
- identifier: vision
  name: Visión
  url: /vision/
  weight: 1
- identifier: principios
  name: Principios
  url: /principios/
  weight: 2
- identifier: principios-estructurales
  name: Estructurales
  url: /principios/estructurales/
  parent: principios
  weight: 1
- identifier: principios-especificos
  name: Específicos
  url: /principios/especificos/
  parent: principios
  weight: 2
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 3
- identifier: organizaciones
  name: Organizaciones
  url: /organizaciones/
  weight: 4
- identifier: algoconsulting
  name: AlgoConsulting
  url: /algoconsulting/
  weight: 5
- identifier: gobernancia
  name: Gobernancia
  url: /gobernancia/
  weight: 6
- identifier: constitucion
  name: Constitución
  url: /gobernancia/constitucion/
  parent: gobernancia
  weight: 1
- identifier: faq
  name: FAQ
  url: /gobernancia/faq/
  parent: gobernancia
  weight: 2
- identifier: la-alianza-en-imagenes
  name: La Alianza en imágenes
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 7
takePart:
- name: "Participar"
  url: "https://portal.algosphere.org"
footer:
- identifier: notas-legales
  name: Notas legales
  url: /notas-legales/
  weight: 1
