main:
- identifier: inicio
  name: Inicio
  url: /
  weight: 1
- identifier: vision
  name: Visión
  url: /vision/
  weight: 2
- identifier: principios
  name: Principios
  url: /principios/
  weight: 3
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 4
- identifier: organizaciones
  name: Organizaciones
  url: /organizaciones/
  weight: 5
- identifier: algoconsulting
  name: AlgoConsulting
  url: /algoconsulting/
  weight: 6
- identifier: gobernancia
  name: Gobernancia
  url: /gobernancia/
  weight: 7
- identifier: la-alianza-en-imagenes
  name: La Alianza en imágenes
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 8
takePart:
- name: "Participar"
  url: "https://portal.algosphere.org/"
footer:
- identifier: notas-legales
  name: Notas legales
  url: /notas-legales/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
