main:
- identifier: vision
  name: Vision
  url: /vision/
  weight: 1
- identifier: positions
  name: Positions
  url: /positions/
  weight: 2
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 3
- identifier: organizations
  name: Organizations
  url: organizations/
  weight: 4
- identifier: algoconsulting
  name: AlgoConsulting
  url: /algoconsulting/
  weight: 5
- identifier: governance
  name: Governance
  url: /governance/
  weight: 6
- identifier: the-alliance-in-images
  name: The Alliance in images
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 7
takepart:
- name: "Take part"
  url: "https://portal.algosphere.org/"
footer:
- identifier: legal-notices
  name: Legal notices
  url: /legal-notices/
  weight: 1
