main:
- identifier: home
  name: Home
  url: /
  weight: 1
- identifier: vision
  name: Vision
  url: /vision/
  weight: 2
- identifier: positions
  name: Positions
  url: /positions/
  weight: 3
- identifier: positions-fundamental
  name: Fundamental
  url: /positions/fundamental/
  parent: positions
  weight: 1
- identifier: positions-specific
  name: Specific
  url: positions/specific/
  parent: positions
  weight: 2
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 4
- identifier: organizations
  name: Organizations
  url: organizations/
  weight: 5
- identifier: algoconsulting
  name: AlgoConsulting
  url: /algoconsulting/
  weight: 6
- identifier: governance
  name: Governance
  url: /governance/
  weight: 7
- identifier: constitution
  name: Constitution
  url: /governance/constitution/
  parent: governance
  weight: 1
- identifier: faq
  name: FAQ
  url: /governance/faq/
  parent: governance
  weight: 2
- identifier: the-alliance-in-images
  name: The Alliance in images
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 8
footer:
- identifier: legal-notices
  name: Legal notices
  url: /legal-notices/
  weight: 1
