baseURL: "https://algo-website.netlify.com/"
languageCode: "en"
defaultContentLanguage: "en"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
enableRobotsTXT: true
params:
  author: "Algosphere"
  twitter: "algosphere"
  facebook: "algosphere"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
disableKinds:
- taxonomy
- taxonomyTerm
languages:
  en:
    languageName: English
    weight: 2
    contentDir: content/en
    title: Algosphere Alliance
    params:
      description: "for the alleviation of suffering"
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
      - identifier: positions
        name: Positions
        url: /positions/
        weight: 3
      - identifier: positions-fundamental
        name: Fundamental
        url: /positions/fundamental/
        parent: positions
        weight: 1
      - identifier: positions-specific
        name: Specific
        url: positions/specific/
        parent: positions
        weight: 2
      - identifier: algonews
        name: AlgoNews
        url: /algonews/
        weight: 4
      - identifier: organizations
        name: Organizations
        url: organizations/
        weight: 5
      - identifier: algoconsulting
        name: AlgoConsulting
        url: /algoconsulting/
        weight: 6
      - identifier: governance
        name: Governance
        url: /governance/
        weight: 7
      - identifier: constitution
        name: Constitution
        url: /governance/constitution/
        parent: governance
        weight: 1
      - identifier: faq
        name: FAQ
        url: /governance/faq/
        parent: governance
        weight: 2
      - identifier: the-alliance-in-images
        name: The Alliance in images
        url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
        weight: 8
      footer:
      - identifier: legal-notices
        name: Legal notices
        url: /legal-notices/
        weight: 1
  fr:
    languageName: Français
    weight: 4
    contentDir: content/fr
    title: Alliance Algosphère
    params:
      description: "pour l'allègement de la souffrance"
    menu:
      main:
      - identifier: accueil
        name: Accueil
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
      - identifier: positions
        name: Positions
        url: /positions/
        weight: 3
      - identifier: positions-structurelles
        name: Structurelles
        url: /positions/structurelles/
        parent: positions
        weight: 1
      - identifier: positions-ponctuelles
        name: Ponctuelles
        url: /positions/ponctuelles/
        parent: positions
        weight: 2
      - identifier: algonews
        name: AlgoNews
        url: /algonews/
        weight: 4
      - identifier: organisations
        name: Organisations
        url: /organisations/
        weight: 5
      - identifier: algoconseil
        name: AlgoConseil
        url: /algoconseil/
        weight: 6
      - identifier: gouvernance
        name: Gouvernance
        url: /gouvernance/
        weight: 7
      - identifier: constitution
        name: Constitution
        url: /gouvernance/constitution/
        parent: gouvernance
        weight: 1
      - identifier: faq
        name: FAQ
        url: /gouvernance/faq/
        parent: gouvernance
        weight: 2
      - identifier: l-alliance-en-images
        name: L'Alliance en images
        url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
        weight: 8
      footer:
      - identifier: mentions-legales
        name: Mentions légales
        url: /mentions-legales/
        weight: 1
  es:
    languageName: Español
    weight: 3
    contentDir: content/es
    title: Alianza Algosfera
    params:
      description: "para el alivio del sufrimiento"
    menu:
      main:
      - identifier: inicio
        name: Inicio
        url: /
        weight: 1
      - identifier: vision
        name: Visión
        url: /vision/
        weight: 2
      - identifier: principios
        name: Principios
        url: /principios/
        weight: 3
      - identifier: principios-estructurales
        name: Estructurales
        url: /principios/estructurales/
        parent: principios
        weight: 1
      - identifier: principios-especificos
        name: Específicos
        url: /principios/especificos/
        parent: principios
        weight: 2
      - identifier: algonews
        name: AlgoNews
        url: /algonews/
        weight: 4
      - identifier: organizaciones
        name: Organizaciones
        url: organizaciones
        weight: 5
      - identifier: algoconsulting
        name: AlgoConsulting
        url: /algoconsulting/
        weight: 6
      - identifier: gobernancia
        name: Gobernancia
        url: /gobernancia/
        weight: 7
      - identifier: constitucion
        name: Constitución
        url: /gobernancia/constitucion/
        parent: gobernancia
        weight: 1
      - identifier: faq
        name: FAQ
        url: /gobernancia/faq/
        parent: gobernancia
        weight: 2
      - identifier: la-alianza-en-imagenes
        name: La Alianza en imágenes
        url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
        weight: 8
      footer:
      - identifier: notas-legales
        name: Notas legales
        url: /notas-legales/
        weight: 1
  de:
    languageName: Deutsch
    weight: 1
    contentDir: content/de
    title: Bündnis Algosphäre
    params:
      description: "zur linderung des leidens"
    menu:
      main:
      - identifier: startseite
        name: Startseite
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
      - identifier: positionen
        name: Positionen
        url: /positionen/
        weight: 3
      - identifier: positionen-grundsaetzliche
        name: Grundsätzliche
        url: /positionen/grundsaetzliche/
        parent: positionen
        weight: 1
      - identifier: positionen-themenbezogene
        name: Themenbezogene
        url: /positionen/themenbezogene/
        parent: positionen
        weight: 2
      - identifier: algonews
        name: AlgoNews
        url: /algonews/
        weight: 4
      - identifier: organisationen
        name: Organisationen
        url: /organisationen/
        weight: 5
      - identifier: algoconsulting
        name: AlgoConsulting
        url: /algoconsulting/
        weight: 6
      - identifier: fuehrung
        name: Führung
        url: /fuehrung/
        weight: 7
      - identifier: grundsatzerklaerung
        name: Grundsatzerklärung
        url: /fuehrung/grundsatzerklaerung/
        parent: fuehrung
        weight: 1
      - identifier: faq
        name: FAQ
        url: /fuehrung/faq/
        parent: fuehrung
        weight: 2
      - identifier: die-allianz-in-bildern
        name: Die Allianz in Bildern
        url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
        weight: 8
      footer:
      - identifier: rechtliche-hinweise
        name: Rechtliche Hinweise
        url: /rechtliche-hinweise/
        weight: 1
