baseURL: "https://algo-website.netlify.com/"
languageCode: "en"
defaultContentLanguage: "en"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
enableRobotsTXT: true
params:
  author: "Algosphere"
  twitter: "algosphere"
  facebook: "algosphere"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
taxonomies:
  category:
  tag:
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    title: Algosphere Alliance
    params:
      description: "for the alleviation of suffering"
    menu:
      main:
      - identifier: blog1
        name: Home
        title: blog section
        url: /blog/
        weight: 1
  fr:
    languageName: Français
    weight: 2
    contentDir: content/fr
    title: Alliance Algosphère
    params:
      description: "pour l'allègement de la souffrance"
    menu:
      main:
      - identifier: blog1
        name: Accueil
        title: blog section
        url: /blog/
        weight: 1
