baseURL: "https://algo-website.netlify.com/"
languageCode: "en"
defaultContentLanguage: "en"
title: "Algosphere Alliance"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
enableRobotsTXT: true
params:
  description: "for the alleviation of suffering"
  author: "Algosphere"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
menu:
  main:
  - identifier: blog1
    name: Accueil
    title: blog section
    url: /blog/
    weight: -110
  - identifier: blog2
    name: Blog
    title: blog section
    url: /blog/
    weight: -110
  - identifier: blog3
    name: Blog
    title: blog section
    url: /blog/
    weight: -110
  - identifier: blog4
    name: Blog
    title: blog section
    url: /blog/
    weight: -110
  - identifier: blog5
    name: Blog
    title: blog section
    url: /blog/
    weight: -110
  - identifier: blog6
    name: Blog
    title: blog section
    url: /blog/
    weight: -110
