baseURL: "https://algo-website.netlify.com/"
languageCode: "en"
defaultContentLanguage: "en"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
enableRobotsTXT: true
params:
  author: "Algosphere"
  twitter: "algosphere"
  facebook: "algosphere"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    title: Algosphere Alliance
    params:
      description: "for the alleviation of suffering"
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
      - identifier: positions
        name: Positions
        url: /positions/
        weight: 3
      - identifier: positions-fundamental
        name: Fundamental
        url: /positions/fundamental/
        weight: 1
        parent: positions
      - identifier: positions-specific
        name: Specific
        url: /positions/specific/
        weight: 2
        parent: positions
      - identifier: algonews
        name: AlgoNews
        url: /algonews/
        weight: 4
      - identifier: organizations
        name: Organizations
        url: /organizations/
        weight: 5
      - identifier: the-alliance-in-images
        name: The Alliance in images
        url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
        weight: 6
      - identifier: governance
        name: Governance
        url: /governance/
        weight: 7
      footer:
      - identifier: legal-notices
        name: Legal notices
        url: /legal-notices/
        weight: 1
  fr:
    languageName: Français
    weight: 2
    contentDir: content/fr
    title: Alliance Algosphère
    params:
      description: "pour l'allègement de la souffrance"
    menu:
      main:
      - identifier: home
        name: Accueil
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
      footer:
      - identifier: mentions-legales
        name: Mentions légales
        url: /mentions-legales/
        weight: 1

  es:
    languageName: Español
    weight: 3
    contentDir: content/es
    title: Alianza Algosfera
    params:
      description: "para el alivio del sufrimiento"
    menu:
      main:
      - identifier: home
        name: Inicio
        url: /
        weight: 1
      - identifier: vision
        name: Vision
        url: /vision/
        weight: 2
