backend:
  name: github
  repo: algosphere/algo-website
  branch: main
site_url: https://algosphere.org
logo_url: https://algosphere.org/images/logo-static/logo-trans.png
locale: "fr"
slug:
  clean_accents: true
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Données"
    name: "data"
    files:
      - label: "Algonews"
        name: "algonews"
        file: "data/algonewsold.yml"
        preview_path: resources/algonews
        fields:
          - label: Publications
            name: issues
            widget: list
            add_to_top: true
            fields:
              - {label: Titre, name: name, widget: string}
              - {label: Année, name: year, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: selection1name, name: selection1name, widget: string}
              - {label: selection1url, name: selection1url, widget: string}
              - {label: selection1namefr, name: selection1namefr, widget: string}
              - {label: selection1urlfr, name: selection1urlfr, widget: string}