backend:
  name: github
  repo: algosphere/algo-website
  branch: main
site_url: https://algosphere.org
logo_url: https://algosphere.org/images/logo-static/logo-trans.png
locale: 'fr'
slug:
  clean_accents: true
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Algonews"
    name: "algonews"
    files:
    - label: "Publications"
      name: "publications"
      file: "data/algonewsold.yml"
      fields:
        - label: Publications
          name: publications
          widget: list
          add_to_top: true
          fields:
            - {label: Titre, name: titre, widget: string}
            - {label: Année, name: annee, widget: string}
            - {label: URL, name: url, widget: string}
