backend:
  name: github
  repo: algosphere/algo-website
  branch: main
site_url: https://algosphere.org
logo_url: https://algosphere.org/images/logo-static/logo-trans.png
locale: "fr"
slug:
  clean_accents: true
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Données"
    name: "data"
    editor:
     preview: false
    files:
      - label: "Algonews"
        name: "algonews"
        file: "data/algonewsold.yml"
        preview_path: resources/algonews
        fields:
          - label: Publications
            name: issues
            widget: list
            add_to_top: true
            fields:
              - {label: Titre, name: title, widget: string}
              - {label: Année, name: year, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Titre extrait (en), name: selection1title, widget: hidden, required: false}
              - {label: URL extrait (en), name: selection1url, widget: hidden, required: false}
              - {label: Titre extrait (fr), name: selection1titlefr, widget: hidden, required: false}
              - {label: URL extrait (fr), name: selection1urlfr, widget: hidden, required: false}