local_backend: false
backend:
  name: github
  repo: algosphere/algo-website
  branch: main
site_url: https://algosphere.org
logo_url: https://algosphere.org/images/logo-static/logo-trans.png
locale: "fr"
search: false
slug:
  clean_accents: true
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Archives"
    name: "archives"
    editor:
      preview: false
    files:
      - label: "Générales"
        name: "general"
        file: "data/archives.yml"
        preview_path: about/archives
        fields:
          - label: Années
            label_singular: année
            name: years
            widget: list
            add_to_top: true
            fields:
              - {label: Année, name: year, widget: string}
              - {label: Archives, name: archives, widget: markdown, buttons: ["bold", "italic", "link", "quote", "bulleted-list", "numbered-list"], editor_components: [], modes: ["rich_text"]}
      - label: "Algonews"
        name: "algonews"
        file: "data/algonewsold.yml"
        preview_path: resources/algonews
        fields:
          - label: Publications
            label_singular: publication
            name: issues
            widget: list
            add_to_top: true
            fields:
              - {label: Titre, name: title, widget: string}
              - {label: Année, name: year, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Titre extrait (en), name: selection1title, widget: hidden, required: false}
              - {label: URL extrait (en), name: selection1url, widget: hidden, required: false}
              - {label: Titre extrait (fr), name: selection1titlefr, widget: hidden, required: false}
              - {label: URL extrait (fr), name: selection1urlfr, widget: hidden, required: false}
  - label: "Alliés"
    name: "allies"
    editor:
      preview: false
    files:
      - label: "Personnes (compteur)"
        name: "allies-people"
        file: "data/allies/people.yml"
        preview_path: allies
        fields:
          - {label: Compteur, name: counter, widget: number, value_type: "int"}
      - label: "Organisations (en)"
        name: "organizations-en"
        file: "data/allies/organizations/en/organizations.yml"
        preview_path: allies
        fields:
          - label: Organisations
            label_singular: organisation
            name: organizations
            widget: list
            fields:
              - {label: Nom, name: name, widget: string}
              - {label: Site, name: website, widget: string}
              - {label: Mission, name: mission, widget: string}
              - {label: Zone, name: zone, widget: string}
              - {label: URL zone, name: zone_link, widget: hidden, required: false}
      - label: "Organisations (fr)"
        name: "organizations-fr"
        file: "data/allies/organizations/fr/organizations.yml"
        preview_path: allies
        fields:
          - label: Organisations
            label_singular: organisation
            name: organizations
            widget: list
            fields:
              - {label: Nom, name: name, widget: string}
              - {label: Site, name: website, widget: string}
              - {label: Mission, name: mission, widget: string}
              - {label: Zone, name: zone, widget: string}
              - {label: URL zone, name: zone_link, widget: hidden, required: false}