main:
- identifier: startseite
  name: Startseite
  url: /
  weight: 1
- identifier: uber
  name: Über
  url: /uber/
  weight: 2
- identifier: vision
  name: Vision
  url: /uber/vision/
  parent: uber
  weight: 1
- identifier: positionen
  name: Positionen
  url: /uber/positionen/
  parent: uber
  weight: 2
- identifier: fuhrung
  name: Führung
  url: /uber/fuhrung/
  parent: uber
  weight: 3
- identifier: die-allianz-in-bildern
  name: Die Allianz in Bildern
  url: /uber/die-allianz-in-bildern
  parent: uber
  weight: 4
- identifier: faq
  name: FAQ
  url: /uber/faq/
  parent: uber
  weight: 5
- identifier: archiv
  name: Archiv
  url: /uber/archiv
  parent: uber
  weight: 6
- identifier: alliierten
  name: Alliierten
  url: /alliierten/
  weight: 3
- identifier: ressourcen
  name: Ressourcen
  url: /ressourcen/
  weight: 4
- identifier: algoconsulting
  name: AlgoConsulting
  url: /ressourcen/algoconsulting/
  parent: ressourcen
  weight: 1
- identifier: algonews
  name: AlgoNews
  url: /ressourcen/algonews/
  parent: ressourcen
  weight: 2
right:
- name: "Kollaboratives Portal"
  pre: "primary-alt"
  url: "https://portal.algosphere.org/"
  weight: 1
- name: "Anmelden"
  pre: "success"
  url: "/anmelden/"
  weight: 2
footer:
- identifier: rechtliche-hinweise
  name: Rechtliche Hinweise
  url: /rechtliche-hinweise/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
- identifier: designevo
  name: Logo by DesignEvo
  url: https://www.designevo.com/"
  weight: 3
