main:
- identifier: accueil
  name: Accueil
  url: /
  weight: 1
- identifier: a-propos
  name: À propos
  url: /a-propos/
  weight: 2
- identifier: vision
  name: Vision
  url: /a-propos/vision/
  parent: a-propos
  weight: 1
- identifier: positions
  name: Positions
  url: /a-propos/positions/
  parent: a-propos
  weight: 2
- identifier: gouvernance
  name: Gouvernance
  url: /a-propos/gouvernance/
  parent: a-propos
  weight: 3
- identifier: l-alliance-en-images
  name: L'Alliance en images
  url: https://docs.google.com/presentation/d/13P2y5H4YtHGopanvrvW5rINO4UM6-F8V4u8uv8jIJyk/edit
  parent: a-propos
  weight: 4
- identifier: faq
  name: FAQ
  url: /a-propos/faq/
  parent: a-propos
  weight: 5
- identifier: archives
  name: Archives
  url: https://docs.google.com/document/d/1O8yNJM5IzMG873rXIqh2SNkTZLlRJUkCX5_3txBepF4/edit
  parent: a-propos
  weight: 6
- identifier: allies
  name: Alliés
  url: /allies/
  weight: 3
- identifier: ressources
  name: Ressources
  url: /ressources/
  weight: 4
- identifier: algoconseil
  name: AlgoConseil
  url: /ressources/algoconseil/
  parent: ressources
  weight: 1
- identifier: algonews
  name: AlgoNews
  url: /ressources/algonews/
  parent: ressources
  weight: 2
right:
- name: "Portail collaboratif"
  pre: "primary-alt"
  url: "https://portal.algosphere.org/fr/"
  weight: 1
- name: "S'inscrire"
  pre: "success"
  url: "https://portal.algosphere.org/fr/register/"
  weight: 2
footer:
- identifier: mentions-legales
  name: Mentions légales
  url: /mentions-legales/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
- identifier: designevo
  name: Logo by DesignEvo
  url: https://www.designevo.com/"
  weight: 3
