main:
- identifier: accueil
  name: Accueil
  url: /
  weight: 1
- identifier: a-propos
  name: À propos
  url: /a-propos/
  weight: 2
- identifier: vision
  name: Vision
  url: /a-propos/vision/
  parent: a-propos
  weight: 1
  icon: "eye"
- identifier: positions
  name: Positions
  url: /a-propos/positions/
  parent: a-propos
  weight: 2
  icon: "flag"
- identifier: gouvernance
  name: Gouvernance
  url: /a-propos/gouvernance/
  parent: a-propos
  weight: 3
  icon: "building"
- identifier: l-alliance-en-images
  name: L'Alliance en images
  url: /a-propos/l-alliance-en-images/
  parent: a-propos
  weight: 4
  icon: "image"
- identifier: faq
  name: FAQ
  url: /a-propos/faq/
  parent: a-propos
  weight: 5
  icon: "question-square"
- identifier: archives
  name: Archives
  url: /a-propos/archives/
  parent: a-propos
  weight: 6
  icon: "archive"
- identifier: allies
  name: Alliés
  url: /allies/
  weight: 3
- identifier: ressources
  name: Ressources
  url: /ressources/
  weight: 4
- identifier: algonews
  name: AlgoNews
  url: /ressources/algonews/
  parent: ressources
  weight: 1
- identifier: algoconseil
  name: AlgoConseil
  url: /ressources/algoconseil/
  parent: ressources
  weight: 2
right:
- name: "Portail collaboratif"
  pre: "primary-alt"
  url: "/portail/"
  weight: 1
- name: "S'inscrire"
  pre: "success"
  url: "/s-inscrire/"
  weight: 2
footer:
- identifier: mentions-legales
  name: Mentions légales
  url: /mentions-legales/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
- identifier: designevo
  name: Logo par DesignEvo
  url: https://www.designevo.com/"
  weight: 3
