main:
- identifier: home
  name: Home
  url: /
  weight: 1
- identifier: about
  name: About
  url: /about/
  weight: 2
- identifier: vision
  name: Vision
  url: /about/vision/
  parent: about
  weight: 1
  icon: "eye"
- identifier: positions
  name: Positions
  url: /about/positions/
  parent: about
  weight: 2
  icon: "flag"
- identifier: governance
  name: Governance
  url: /about/governance/
  parent: about
  weight: 3
  icon: "building"
- identifier: the-alliance-in-images
  name: The Alliance in images
  url: /about/the-alliance-in-images/
  parent: about
  weight: 4
  icon: "image"
- identifier: faq
  name: FAQ
  url: /about/faq/
  parent: about
  weight: 5
  icon: "question-square"
- identifier: archives
  name: Archives
  url: /about/archives/
  parent: about
  weight: 6
  icon: "archive"
- identifier: allies
  name: Allies
  url: /allies/
  weight: 3
- identifier: resources
  name: Resources
  url: /resources/
  weight: 4
- identifier: algonews
  name: AlgoNews
  url: /resources/algonews/
  parent: resources
  weight: 1
- identifier: algoconsulting
  name: AlgoConsulting
  url: /resources/algoconsulting/
  parent: resources
  weight: 2
right:
- name: "Collaborative portal"
  pre: "primary-alt"
  url: "/portal/"
  weight: 1
- name: "Sign Up"
  pre: "success"
  url: "/signup/"
  weight: 2
footer:
- identifier: legal-notices
  name: Legal notices
  url: /legal-notices/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
- identifier: designevo
  name: Logo by DesignEvo
  url: https://www.designevo.com/"
  weight: 3
