main:
- identifier: inicio
  name: Inicio
  url: /
  weight: 1
- identifier: informacion
  name: Información
  url: /informacion/
  weight: 2
- identifier: vision
  name: Visión
  url: /informacion/vision/
  parent: informacion
  weight: 1
- identifier: principios
  name: Principios
  url: /informacion/principios/
  parent: informacion
  weight: 2
- identifier: gobernancia
  name: Gobernancia
  url: /informacion/gobernancia/
  parent: informacion
  weight: 3
- identifier: la-alianza-en-imagenes
  name: La Alianza en imágenes
  url: /informacion/la-alianza-en-imagenes
  parent: informacion
  weight: 4
- identifier: faq
  name: FAQ
  url: /informacion/faq/
  parent: informacion
  weight: 5
- identifier: archivos
  name: Archivos
  url: /informacion/archivos
  parent: informacion
  weight: 6
- identifier: aliados
  name: Aliados
  url: /aliados/
  weight: 3
- identifier: recursos
  name: Recursos
  url: /recursos/
  weight: 4
- identifier: algoconsulting
  name: AlgoConsulting
  url: /recursos/algoconsulting/
  parent: recursos
  weight: 1
- identifier: algonews
  name: AlgoNews
  url: /recursos/algonews/
  parent: recursos
  weight: 2
right:
- name: "Portal colaborativo"
  pre: "primary-alt"
  url: "https://portal.algosphere.org/"
  weight: 1
- name: "Registrarse"
  pre: "success"
  url: "/registrarse/"
  weight: 2
footer:
- identifier: notas-legales
  name: Notas legales
  url: /notas-legales/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
- identifier: designevo
  name: Logo by DesignEvo
  url: https://www.designevo.com/"
  weight: 3
