name: ci-cd-develop

on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 0 * * *'

env:
  CI: true
  NODE_VERSION_: '12.14.0'
  HUGO_VERSION: '0.61.0'
  
jobs:
  test-env:
    name: Test environment variables
    runs-on: windows-latest
    steps:
    - run: echo 1. NODE_VERSION  
        
  build-deploy:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 12.14.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.0'
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer netlify-cli
      if: success()
    - name: Setup Hugo 0.61.0
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.61.0'
        extended: true
      if: success()
    - name: Build site
      run: hugo
      if: success()
    - name: Post-formatting
      run: gulp
      if: success()
