name: CI/CD develop

on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 0 * * *'

env:
  CI: true
  NODE_VERSION: '12.14.0'
  HUGO_VERSION: '0.61.0'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js $NODE_VERSION
      uses: actions/setup-node@v1
      with:
        node-version: '$NODE_VERSION'
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo $HUGO_VERSION
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '$HUGO_VERSION'
        extended: true
      if: success()
    - name: Build site
      run: hugo
      if: success()
    - name: Post-formatting
      run: gulp
      if: success()
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git checkout preview
        rm -rf *
        git merge develop
      if: success()
