name: ci-cd-develop

on:
  push:
    branches:
      - develop

env:
  PREVIEW: true
  NODE_VERSION: '12.14.0'
  HUGO_VERSION: '0.64.0'
  NETLIFY_SITE_ID: 'c97298da-938f-4084-9307-c7135a92f98a'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_WEBSITE }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  ALGOLIA_APPLICATION_ID: ${{ secrets. ALGOLIA_APPLICATION_ID }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  ALGOLIA_INDEX: 'preview'
  ALGOLIA_CONFIG: 'algolia-config-dev.json'

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-dev
      if: success()
    - name: Deploy site
      uses: netlify/actions/cli@master
      with:
        args: "deploy --prod --dir public"
      if: success()
    - name: Notify Discord on failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        text: CI/CD failed
        webhookUrl: ${{ env.DISCORD_WEBHOOK }}
