name: deploy-dev

on:
  push:
    branches:
      - dev

env:
  DEV: true
  HUGO_VERSION: '0.92.0'
  NODE_VERSION: '16.13.2'
  NETLIFY_SITE_ID: 'c97298da-938f-4084-9307-c7135a92f98a'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_WEBSITE }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g postcss postcss-cli autoprefixer gulp-cli netlify-cli
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run _build-dev
      if: success()
    - name: Deploy site
      run: npm run _deploy
      if: success()
