name: deploy-dev

on:
  push:
    branches:
      - dev

env:
  PREVIEW: true
  HUGO_VERSION: '0.74.1'
  NODE_VERSION: '12.14.0'
  NETLIFY_SITE_ID: 'c97298da-938f-4084-9307-c7135a92f98a'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_WEBSITE }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss postcss-cli autoprefixer netlify-cli
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-dev
      if: success()
    - name: Deploy site
      run: npm run deploy
      if: success()
